### ISSUE TITLE
Crashing while scrolling through a list of cached images, while offline

### ISSUE THREAD

**Issue by diogowbrito** [melvitax/AFImageHelper#15]
`imageFromURL` crashes when scrolling through a list of images while offline.
The images were previously loaded and caches.

I was able to trace the error to an explicit bang here:
```  if let image = UIImage(data: data!) {```

After checking for data the app seemed to work ok.

I already submitted a PR that seems to fix the issue.

**Comment by melvitax** [comment]
Thanks
